import type { CSSProperties } from 'react';

// Shared style atoms for the mobile layout. Kept as plain objects (not CSS
// classes) so this stays dependency-free and works with the inline-style
// pattern used across the rest of the web app.
export const M = {
  page: {
    minHeight: '100vh',
    background: 'var(--bg)',
    color: 'var(--text)',
    fontFamily: 'var(--ui)',
    paddingTop: 'calc(env(safe-area-inset-top))',
    paddingBottom: 'calc(76px + env(safe-area-inset-bottom))',
  },
  scroll: { padding: '12px 14px 0' },
  header: {
    position: 'sticky',
    top: 0,
    zIndex: 5,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '14px 14px 10px',
    background: 'color-mix(in oklab, var(--bg) 92%, transparent)',
    backdropFilter: 'blur(10px)',
    borderBottom: '1px solid var(--border)',
    paddingTop: 'calc(14px + env(safe-area-inset-top))',
  },
  title: { fontSize: 17, fontWeight: 700, letterSpacing: -0.2 },
  card: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 14,
    padding: '16px 16px',
  },
  eyebrow: {
    fontSize: 10,
    color: 'var(--muted)',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    marginBottom: 6,
  },
  section: {
    fontSize: 11,
    color: 'var(--muted)',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    margin: '18px 4px 8px',
  },
  segGroup: {
    display: 'inline-flex',
    background: 'var(--surface-2)',
    padding: 3,
    borderRadius: 8,
    border: '1px solid var(--border)',
  },
  segBtn: {
    border: 'none',
    background: 'transparent',
    fontFamily: 'var(--mono)',
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--muted)',
    padding: '5px 10px',
    borderRadius: 6,
    cursor: 'pointer',
  },
  segBtnActive: {
    background: 'var(--surface)',
    color: 'var(--text)',
    boxShadow: '0 1px 2px rgba(0,0,0,0.12)',
  },
  iconBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--surface)',
    color: 'var(--text)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  pillRow: {
    display: 'flex',
    gap: 6,
    overflowX: 'auto' as const,
    WebkitOverflowScrolling: 'touch',
    paddingBottom: 4,
  },
  pillBtn: {
    flexShrink: 0,
    border: '1px solid var(--border)',
    background: 'transparent',
    color: 'var(--muted)',
    fontFamily: 'var(--mono)',
    fontSize: 11,
    fontWeight: 600,
    padding: '6px 12px',
    borderRadius: 999,
    cursor: 'pointer',
    letterSpacing: 0.3,
  },
  pillBtnActive: {
    color: 'var(--text)',
    background: 'var(--surface-2)',
    borderColor: 'var(--text)',
  },
  empty: {
    padding: 24,
    textAlign: 'center',
    color: 'var(--muted)',
    fontSize: 12,
  },
} satisfies Record<string, CSSProperties>;
